# Variables
@baseUrl = http://localhost:3333

# Server Health Check
GET {{baseUrl}}/health

###

# Get Rooms
get {{baseUrl}}/rooms

###

# Create Room
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Room Name Test",
  "description": "Room Description Test"
}